// <auto-generated />
namespace TechLead.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddUserProprieties_Job_FirstRegistration_Points : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddUserProprieties_Job_FirstRegistration_Points));
        
        string IMigrationMetadata.Id
        {
            get { return "201908311901082_AddUserProprieties_Job_FirstRegistration_Points"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
