// <auto-generated />
namespace TechLead.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class UpdateSubmissionTable_AddDefaultValuesToScoresAndExecutionTime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UpdateSubmissionTable_AddDefaultValuesToScoresAndExecutionTime));
        
        string IMigrationMetadata.Id
        {
            get { return "201908012106470_UpdateSubmissionTable_AddDefaultValuesToScoresAndExecutionTime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
